<!doctype html>
<html lang="fr">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Connexion salarié</title>
    <link rel="icon" type="image/x-icon" href="{{ asset('images/branding/smartrh-icon.ico') }}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ asset('images/branding/smartrh-icon.png') }}">
    <link rel="apple-touch-icon" href="{{ asset('images/branding/smartrh-icon.png') }}">
    <style>:root{--sr-deep:#0B2E33;--sr-deep-teal:#0F3D3E;--sr-primary:#0F766E;--sr-primary-hover:#0F5F59;--sr-bg:#0B1220;--sr-card:#182235;--sr-border:#2B3A52;--sr-text:#F8FAFC;--sr-muted:#CBD5E1;--sr-gold:#D4A72C}*{box-sizing:border-box}body{font-family:Inter,Segoe UI,Arial,sans-serif;background:radial-gradient(circle at top left,rgba(20,184,166,.10),transparent 30rem),radial-gradient(circle at top right,rgba(212,167,44,.07),transparent 24rem),var(--sr-bg);display:grid;min-height:100vh;place-items:center;margin:0;color:var(--sr-text)}.card{background:var(--sr-card);border:1px solid var(--sr-border);border-radius:16px;padding:30px;width:min(440px,92vw);box-shadow:0 24px 54px rgba(0,0,0,.30)}.brand{display:flex;align-items:center;gap:12px;font-weight:900;color:var(--sr-text)}.brand img{width:46px;height:46px;object-fit:contain;filter:drop-shadow(0 8px 18px rgba(0,0,0,.22))}.brand:after{content:"";height:2px;width:52px;border-radius:999px;background:linear-gradient(90deg,#14B8A6,var(--sr-gold));margin-left:auto}h1{margin:24px 0 8px;color:var(--sr-text);letter-spacing:0}.muted{color:var(--sr-muted);line-height:1.6}input{width:100%;padding:12px;margin:8px 0 14px;border:1px solid #374151;border-radius:10px;background:#111827;color:var(--sr-text)}input:focus{outline:3px solid rgba(20,184,166,.22);border-color:#14B8A6}.btn{width:100%;background:var(--sr-primary);color:white;border:0;border-radius:10px;padding:13px;font-weight:850;cursor:pointer}.btn:hover{background:var(--sr-primary-hover)}label{font-weight:750;color:var(--sr-muted)}.error{color:#FCA5A5}</style>
</head>
<body><form class="card" method="post" action="{{ route('employee.authenticate') }}">@csrf<div class="brand"><img src="{{ asset('images/branding/smartrh-icon.png') }}" alt="{{ config('smartrh.product_name') }}">{{ config('smartrh.product_name') }}</div><h1>Portail salarié</h1><p class="muted">Accédez à vos bulletins, documents RH et demandes de congé.</p>@error('email')<p class="error">{{ $message }}</p>@enderror<label>Email</label><input name="email" type="email" autocomplete="email" required><label>Mot de passe</label><input name="password" type="password" autocomplete="current-password" required><button class="btn">Se connecter</button><p class="muted">Support: {{ config('smartrh.support_phone') }}</p></form></body></html>
